# Staff Permissions
staffPermission: monolith.staff
modPermission: monolith.mod
adminPermission: monolith.admin
devPermission: monolith.dev

# Staff Tools
moderatingItem: FLINT
debuggingItem: DEBUG_STICK

# Build Repository
buildRepositoryBox: ~
buildRepositoryOrientation: ~

# Maintenance Mode
maintenanceMode: false
maintenanceModePermission: monolith.staff

# Miscellaneous
shutdownMessage: The server is going down for maintenance.

tipsPeriodInMinutes: 10
tips:
  - Any feedback? Please let us know at discord.link.here!








# ENTITY SERVICES
baseHealth: 20

# WORLD SERVICE
worldDirectoryName: world
netherDirectoryName: world_nether
endDirectoryName: world_the_end
