name: "WarCraft_Monolith"
version: "14.0.0-SNAPSHOT"
author: fishb6nes
authors: [fishb6nes, cbngu]
website: http://warcraft.gg

api-version: "1.15"
main: gg.warcraft.monolith.spigot.MonolithPlugin
depend: [EffectLib]
loadbefore: [EssentialsX]
